default:
  - lint
test:
  - karma:once:start
test-watch:
  - karma:watch:start
  - watch:tests
test-ci:
  - karma:ci:start
lint:
  - jshint
  - jscs
  - lintspaces
lint:code:
  - jshint:code
  - jscs:code
  - lintspaces:code
lint:grunt:
  - jshint:grunt
  - jscs:grunt
  - lintspaces:grunt
